# Generated by Django 3.2.12 on 2024-03-08 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Type 1', 'Type 1'), ('Type 2', 'Type 2'), ('Type 3', 'Type 3')], max_length=50)),
                ('frequency', models.CharField(choices=[('Frequency 1', 'Frequency 1'), ('Frequency 2', 'Frequency 2'), ('Frequency 3', 'Frequency 3')], max_length=50)),
                ('prf', models.CharField(max_length=100)),
                ('pw_usec', models.IntegerField()),
            ],
        ),
    ]
